export const CREATE_WINERY = "CREATE_WINERY";
export const CREATE_WINERY_SUCCESS = "CREATE_WINERY_SUCCESS";
export const EDIT_WINERY = "EDIT_WINERY";
export const EDIT_WINERY_SUCCESS = "EDIT_WINERY_SUCCESS";
export const GET_WINERIES_SUCCESS = "GET_WINERIES_SUCCES";